---
all:
  vars:
    cartridge_app_name: distributed-kv-storage
    cartridge_package_path: ./distributed-kv-storage-0.1.0-0-g7005fc0.rpm

    cartridge_cluster_cookie: app-default-cookie

    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_ssh_common_args: '-o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

  # define instances
  hosts:
    router-1:
      advertise_uri: '172.19.0.2:3301'
      http_port: 8800

    kv-storage-1-master:
      advertise_uri: '172.19.0.2:3301'
      http_port: 8801

    kv-storage-1-replica-1:
      advertise_uri: '172.19.0.3:3301'
      http_port: 8802

    kv-storage-1-replica-2:
      advertise_uri: '172.19.0.3:3301'
      http_port: 8803

  # instances' groups
  children:
    # host-1 group
    host-1:
      vars:
        ansible_host: 172.19.0.2
        ansible_user: vagrant
      hosts:
        router-1:
        kv-storage-1-master:

    # host-2 group
    host-2:
      vars:
        ansible_host: 172.19.0.3
        ansible_user: vagrant
      hosts:
        kv-storage-1-replica-1:
        kv-storage-1-replica-2:

    # replica-app-1 group
    replicaset-app-1:
      vars:
        replicaset_alias: router-1
        failover_priority:
          - router-1
        roles:
          - 'api'

      hosts:
        - router-1:

    # replicaset-kv-storage-1 group
    replicaset-kv-storage-1:
      vars:
        replicaset_alias: kv-storage-1
        weight: 4
        failover_priority:
          - kv-storage-1-master
          - kv-storage-1-replica-1
          - kv-storage-1-replica-1
        roles:
          - 'storage'

      hosts:
        kv-storage-1-master:
        kv-storage-1-replica-1:
        kv-storage-1-replica-2:
